# Generated by Django 5.1.5 on 2025-02-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra_ospo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutspiospo',
            options={'verbose_name': 'О кафедре ОСПО', 'verbose_name_plural': 'О кафедре ОСПО'},
        ),
        migrations.AlterModelOptions(
            name='awardospo',
            options={'verbose_name': 'Награда ОСПО', 'verbose_name_plural': 'Награды ОСПО'},
        ),
        migrations.AlterModelOptions(
            name='contactospo',
            options={'verbose_name': 'Контакт ОСПО', 'verbose_name_plural': 'Контакты ОСПО'},
        ),
        migrations.AlterModelOptions(
            name='departmentospo',
            options={'verbose_name': 'ОСПО', 'verbose_name_plural': 'ОСПО'},
        ),
        migrations.AlterModelOptions(
            name='teacherospo',
            options={'verbose_name': 'Преподаватель ОСПО', 'verbose_name_plural': 'Преподаватели ОСПО'},
        ),
    ]
