# Generated by Django 5.1.5 on 2025-02-05 06:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutspiOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutspi_images/')),
            ],
            options={
                'verbose_name': 'О кафедре ОСПО',
                'verbose_name_plural': 'О кафедре ОСПО',
            },
        ),
        migrations.CreateModel(
            name='AwardOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='awards/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Награда ОСПО',
                'verbose_name_plural': 'Награды ОСПО',
            },
        ),
        migrations.CreateModel(
            name='ContactOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Контакт ОСПО',
                'verbose_name_plural': 'Контакты ОСПО',
            },
        ),
        migrations.CreateModel(
            name='DepartmentOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ОСПО',
                'verbose_name_plural': 'ОСПО',
            },
        ),
        migrations.CreateModel(
            name='ODDocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='Unknown', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bio', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers_photos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Преподаватель ОСПО',
                'verbose_name_plural': 'Преподаватели ОСПО',
            },
        ),
    ]
