# Generated by Django 5.1.5 on 2025-02-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra_od', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutspiod',
            options={'verbose_name': 'О кафедре ОГиЕМД', 'verbose_name_plural': 'О кафедре ОГиЕМД'},
        ),
        migrations.AlterModelOptions(
            name='awardod',
            options={'verbose_name': 'Награда ОГиЕМД', 'verbose_name_plural': 'Награды ОГиЕМД'},
        ),
        migrations.AlterModelOptions(
            name='contactod',
            options={'verbose_name': 'Контакт ОГиЕМД', 'verbose_name_plural': 'Контакты ОГиЕМД'},
        ),
        migrations.AlterModelOptions(
            name='teacherod',
            options={'verbose_name': 'Преподаватель ОГиЕМД', 'verbose_name_plural': 'Преподаватели ОГиЕМД'},
        ),
    ]
